### ISSUE TITLE
Parsing a more complex scad file

### ISSUE THREAD

**Issue by kasbah** [bgamari/language-openscad#1]
Hey, I was wondering about how much of OpenSCAD can be parsed by this parser as I am considering using it for [a project](https://github.com/libfive/libfive/issues/310). I tried running [a more complicated scad file](https://gitlab.com/openflexure/openflexure-microscope/blob/master/openscad/main_body.scad) and it fails:

```
Remaining: " \n\n\nmodule leg(brace=stage_flex_w){\n    \n    \n   ...
```

I tried removing `use` and `import` stuff but it doesn't seem to help. Any ideas?

**Comment by bgamari** [comment]
Having a look now.

**Comment by bgamari** [comment]
With the last commit the given example parses as the attached value (produced by `ppsh --html`).
[main_body.scad.zip](https://github.com/bgamari/language-openscad/files/3720218/main_body.scad.zip)

**Comment by bgamari** [comment]
Broadly speaking, this is a project that I never really had the time to finish. I believe that with the last few patches the grammar is mostly complete (insofar as it is specified) but I wouldn't doubt that there are still corner cases. Do feel free to submit additional issues as you find them.

**Comment by bgamari** [comment]
Also, I just pushed a patch I found hanging around turning `Test.hs` into a proper golden testsuite driver. In principle you can add any tests you find to the `tests/` directory and accept the parsed output with `cabal new-test --test-option=--accept`.

**Comment by kasbah** [comment]
Thanks very much, just got around to checking if I can parse this file now and it works.
